{% set name = "fastscapelib-f2py" %}
{% set version = "2.8.2" %}
{% set sha256 = "425e9e8003ce7dff5027ccc1f2c817933e9f0f6d68dff41b6b4b6357ec7d1586" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fastscape-lem/fastscapelib-fortran/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - fastscapelib-fortran.patch

build:
  number: 6

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - scikit-build                           # [build_platform != target_platform]
    - {{ compiler('fortran') }}  # [not win]
    - flang =5.0                 # [win]
    - {{ compiler('c') }}
    - cmake
    - make           # [linux]
  host:
    - python
    - scikit-build
    - pip
    - wheel
    - setuptools
    - numpy
    - nomkl          # [win]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - libflang =5.0  # [win]
    - nomkl          # [win]

test:
  imports:
    - fastscapelib_fortran

about:
  home: https://github.com/fastscape-lem/fastscapelib-fortran
  license: GPL-3.0-only
  license_file: LICENSE
  summary: 'Library for landscape evolution modeling (Python bindings)'
  description: |
    A Fortran library that implements efficient algorithms
    for landscape evolution modeling.
    This conda package provides Python bindings (compiled using f2py).

extra:
  recipe-maintainers:
    - benbovy
